# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\hs\Desktop\PyQt5_FES\SerialPort_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(669, 514)
        font = QtGui.QFont()
        font.setFamily("方正兰亭中黑_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Form.setMouseTracking(False)
        Form.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(192, 222, 194);\n"
"font: 9pt \"方正兰亭中黑_GBK\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 71, 21))
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 280, 54, 20))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.Send_Button = QtWidgets.QPushButton(Form)
        self.Send_Button.setGeometry(QtCore.QRect(330, 280, 75, 23))
        self.Send_Button.setStyleSheet("color: rgb(0, 0, 0);")
        self.Send_Button.setObjectName("Send_Button")
        self.ClearButton = QtWidgets.QPushButton(Form)
        self.ClearButton.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.ClearButton.setStyleSheet("color: rgb(0, 0, 0);")
        self.ClearButton.setObjectName("ClearButton")
        self.textEdit_Recive = QtWidgets.QTextEdit(Form)
        self.textEdit_Recive.setGeometry(QtCore.QRect(40, 80, 361, 151))
        self.textEdit_Recive.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_Recive.setObjectName("textEdit_Recive")
        self.textEdit_Send = QtWidgets.QTextEdit(Form)
        self.textEdit_Send.setGeometry(QtCore.QRect(40, 310, 361, 151))
        self.textEdit_Send.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(440, 100, 221, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Com_Baud_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Com_Baud_Label.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Baud_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Baud_Label.setObjectName("Com_Baud_Label")
        self.gridLayout.addWidget(self.Com_Baud_Label, 1, 0, 1, 1)
        self.Com_Close_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Com_Close_Button.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Close_Button.setDefault(False)
        self.Com_Close_Button.setObjectName("Com_Close_Button")
        self.gridLayout.addWidget(self.Com_Close_Button, 4, 1, 1, 1)
        self.Com_Name_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Com_Name_Label.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Name_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Name_Label.setObjectName("Com_Name_Label")
        self.gridLayout.addWidget(self.Com_Name_Label, 2, 0, 1, 1)
        self.Com_Name_Combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.Com_Name_Combo.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Name_Combo.setObjectName("Com_Name_Combo")
        self.gridLayout.addWidget(self.Com_Name_Combo, 2, 1, 1, 1)
        self.Com_Refresh_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Com_Refresh_Label.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Refresh_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Refresh_Label.setObjectName("Com_Refresh_Label")
        self.gridLayout.addWidget(self.Com_Refresh_Label, 0, 0, 1, 1)
        self.Com_Refresh_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Com_Refresh_Button.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Refresh_Button.setObjectName("Com_Refresh_Button")
        self.gridLayout.addWidget(self.Com_Refresh_Button, 0, 1, 1, 1)
        self.Com_State_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Com_State_Label.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_State_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_State_Label.setObjectName("Com_State_Label")
        self.gridLayout.addWidget(self.Com_State_Label, 3, 0, 1, 1)
        self.Com_Baud_Combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.Com_Baud_Combo.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Baud_Combo.setEditable(True)
        self.Com_Baud_Combo.setDuplicatesEnabled(False)
        self.Com_Baud_Combo.setModelColumn(0)
        self.Com_Baud_Combo.setObjectName("Com_Baud_Combo")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.gridLayout.addWidget(self.Com_Baud_Combo, 1, 1, 1, 1)
        self.Com_Open_Button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Com_Open_Button.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Open_Button.setObjectName("Com_Open_Button")
        self.gridLayout.addWidget(self.Com_Open_Button, 3, 1, 1, 1)
        self.Com_isOpenOrNot_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.Com_isOpenOrNot_Label.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_isOpenOrNot_Label.setText("")
        self.Com_isOpenOrNot_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_isOpenOrNot_Label.setObjectName("Com_isOpenOrNot_Label")
        self.gridLayout.addWidget(self.Com_isOpenOrNot_Label, 4, 0, 1, 1)
        self.hexSending_checkBox = QtWidgets.QCheckBox(Form)
        self.hexSending_checkBox.setGeometry(QtCore.QRect(240, 280, 81, 20))
        self.hexSending_checkBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.hexSending_checkBox.setObjectName("hexSending_checkBox")
        self.hexShowing_checkBox = QtWidgets.QCheckBox(Form)
        self.hexShowing_checkBox.setGeometry(QtCore.QRect(240, 40, 81, 20))
        self.hexShowing_checkBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.hexShowing_checkBox.setObjectName("hexShowing_checkBox")
        self.About_Button = QtWidgets.QPushButton(Form)
        self.About_Button.setGeometry(QtCore.QRect(440, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("方正兰亭中黑_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.About_Button.setFont(font)
        self.About_Button.setStyleSheet("color: rgb(0, 0, 0);")
        self.About_Button.setObjectName("About_Button")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(440, 360, 221, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_Wavelength = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Wavelength.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_Wavelength.setObjectName("lineEdit_Wavelength")
        self.gridLayout_4.addWidget(self.lineEdit_Wavelength, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 2, 1, 1)
        self.Com_isOpenOrNot_Label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Com_isOpenOrNot_Label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_isOpenOrNot_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_isOpenOrNot_Label_2.setObjectName("Com_isOpenOrNot_Label_2")
        self.gridLayout_4.addWidget(self.Com_isOpenOrNot_Label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 2, 1, 1)
        self.lineEdit_Break = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Break.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_Break.setObjectName("lineEdit_Break")
        self.gridLayout_4.addWidget(self.lineEdit_Break, 4, 3, 1, 1)
        self.lineEdit_Value = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Value.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_Value.setObjectName("lineEdit_Value")
        self.gridLayout_4.addWidget(self.lineEdit_Value, 0, 3, 1, 1)
        self.Com_State_Label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Com_State_Label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_State_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_State_Label_2.setObjectName("Com_State_Label_2")
        self.gridLayout_4.addWidget(self.Com_State_Label_2, 4, 0, 1, 1)
        self.Com_Baud_Label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Com_Baud_Label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Baud_Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Baud_Label_2.setObjectName("Com_Baud_Label_2")
        self.gridLayout_4.addWidget(self.Com_Baud_Label_2, 0, 0, 1, 1)
        self.lineEdit_Take = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Take.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_Take.setObjectName("lineEdit_Take")
        self.gridLayout_4.addWidget(self.lineEdit_Take, 5, 3, 1, 1)
        self.lineEdit_Frequency = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_Frequency.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit_Frequency.setObjectName("lineEdit_Frequency")
        self.gridLayout_4.addWidget(self.lineEdit_Frequency, 4, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 0, 1, 1, 1)
        self.Com_Indeed_Button = QtWidgets.QPushButton(Form)
        self.Com_Indeed_Button.setGeometry(QtCore.QRect(327, 470, 81, 26))
        self.Com_Indeed_Button.setStyleSheet("color: rgb(0, 0, 0);")
        self.Com_Indeed_Button.setObjectName("Com_Indeed_Button")
        self.radioButton_1 = QtWidgets.QRadioButton(Form)
        self.radioButton_1.setGeometry(QtCore.QRect(440, 310, 41, 16))
        self.radioButton_1.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(490, 310, 41, 16))
        self.radioButton_2.setTabletTracking(False)
        self.radioButton_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Form)
        self.radioButton_3.setGeometry(QtCore.QRect(540, 310, 41, 16))
        self.radioButton_3.setTabletTracking(False)
        self.radioButton_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Form)
        self.radioButton_4.setGeometry(QtCore.QRect(590, 310, 41, 16))
        self.radioButton_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.textEdit_tip = QtWidgets.QTextEdit(Form)
        self.textEdit_tip.setGeometry(QtCore.QRect(550, 330, 111, 21))
        self.textEdit_tip.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_tip.setObjectName("textEdit_tip")
        self.textEdit_tip_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_tip_2.setGeometry(QtCore.QRect(440, 330, 111, 21))
        self.textEdit_tip_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_tip_2.setObjectName("textEdit_tip_2")
        self.textEdit_Recive.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.Send_Button.raise_()
        self.ClearButton.raise_()
        self.textEdit_Send.raise_()
        self.gridLayoutWidget.raise_()
        self.hexSending_checkBox.raise_()
        self.hexShowing_checkBox.raise_()
        self.About_Button.raise_()
        self.gridLayoutWidget_2.raise_()
        self.Com_Indeed_Button.raise_()
        self.radioButton_1.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.textEdit_tip.raise_()
        self.textEdit_tip_2.raise_()

        self.retranslateUi(Form)
        self.ClearButton.clicked.connect(self.textEdit_Recive.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "接收区"))
        self.label_2.setText(_translate("Form", "发送区"))
        self.Send_Button.setText(_translate("Form", "发送"))
        self.ClearButton.setText(_translate("Form", "清除"))
        self.textEdit_Recive.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正兰亭中黑_GBK\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_Send.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正兰亭中黑_GBK\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Com_Baud_Label.setText(_translate("Form", "波特率"))
        self.Com_Close_Button.setText(_translate("Form", "Close"))
        self.Com_Name_Label.setText(_translate("Form", "串口选择"))
        self.Com_Refresh_Label.setText(_translate("Form", "串口搜索"))
        self.Com_Refresh_Button.setText(_translate("Form", "刷新"))
        self.Com_State_Label.setText(_translate("Form", "串口操作"))
        self.Com_Baud_Combo.setCurrentText(_translate("Form", "115200"))
        self.Com_Baud_Combo.setItemText(0, _translate("Form", "115200"))
        self.Com_Baud_Combo.setItemText(1, _translate("Form", "1200"))
        self.Com_Baud_Combo.setItemText(2, _translate("Form", "2400"))
        self.Com_Baud_Combo.setItemText(3, _translate("Form", "4800"))
        self.Com_Baud_Combo.setItemText(4, _translate("Form", "9600"))
        self.Com_Baud_Combo.setItemText(5, _translate("Form", "14400"))
        self.Com_Baud_Combo.setItemText(6, _translate("Form", "19200"))
        self.Com_Baud_Combo.setItemText(7, _translate("Form", "38400"))
        self.Com_Baud_Combo.setItemText(8, _translate("Form", "43000"))
        self.Com_Baud_Combo.setItemText(9, _translate("Form", "57600"))
        self.Com_Baud_Combo.setItemText(10, _translate("Form", "76800"))
        self.Com_Baud_Combo.setItemText(11, _translate("Form", "128000"))
        self.Com_Baud_Combo.setItemText(12, _translate("Form", "230400"))
        self.Com_Baud_Combo.setItemText(13, _translate("Form", "256000"))
        self.Com_Baud_Combo.setItemText(14, _translate("Form", "460800"))
        self.Com_Baud_Combo.setItemText(15, _translate("Form", "921600"))
        self.Com_Baud_Combo.setItemText(16, _translate("Form", "1382400"))
        self.Com_Open_Button.setText(_translate("Form", "Open"))
        self.hexSending_checkBox.setText(_translate("Form", "16进制发送"))
        self.hexShowing_checkBox.setText(_translate("Form", "16进制显示"))
        self.About_Button.setText(_translate("Form", "Made by PyQt5 "))
        self.label_5.setText(_translate("Form", "占空比"))
        self.Com_isOpenOrNot_Label_2.setText(_translate("Form", "波宽"))
        self.label_3.setText(_translate("Form", "幅值"))
        self.label_4.setText(_translate("Form", "通断比"))
        self.Com_State_Label_2.setText(_translate("Form", "频率"))
        self.Com_Baud_Label_2.setText(_translate("Form", "工作使能"))
        self.comboBox.setItemText(0, _translate("Form", "工作"))
        self.comboBox.setItemText(1, _translate("Form", "停止"))
        self.Com_Indeed_Button.setText(_translate("Form", "确认"))
        self.radioButton_1.setText(_translate("Form", "通道1"))
        self.radioButton_2.setText(_translate("Form", "通道2"))
        self.radioButton_3.setText(_translate("Form", "通道3"))
        self.radioButton_4.setText(_translate("Form", "通道4"))
        self.textEdit_tip.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正兰亭中黑_GBK\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_tip_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'方正兰亭中黑_GBK\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; color:#000000;\">请先输入数据后点击相应通道</span></p></body></html>"))
